INSERT INTO prestador (contratante_id, nome, email, fone, avatar) VALUES
	('1', 'Alexandre Cunha', 'evelyn61@uol.com.br', '43975405169', './Assets/avatar3.jpg'),
	('2', 'Gabriela da Rosa', 'camposmaria@gmail.com', '43910392686', './Assets/avatar3.jpg'),
	('3', 'Heloísa Melo', 'luiz-gustavo44@uol.com.br', '43974850813', './Assets/avatar5.jpg'),
	('4', 'Marina Silveira', 'xfarias@ig.com.br', '43988526926', './Assets/avatar2.jpg'),
	('5', 'Luiz Fernando da Mota', 'camposmariane@uol.com.br', '43910503527', './Assets/avatar4.jpg'),
	('6', 'Eduardo Vieira', 'nicoleda-rocha@ig.com.br', '43972151706', './Assets/avatar6.jpg'),
	('7', 'Danilo Pereira', 'gustavoda-conceicao@uol.com.br', '43942099562', './Assets/avatar2.jpg'),
	('8', 'Agatha da Cunha', 'odas-neves@hotmail.com', '43926274454', './Assets/avatar1.jpg'),
	('9', 'Olivia Araújo', 'heloisa77@yahoo.com.br', '43945411427', './Assets/avatar4.jpg'),
	('10', 'Nicolas Teixeira', 'joao-miguel49@ig.com.br', '43957494510', './Assets/avatar5.jpg'),
	('11', 'João Gabriel da Rosa', 'teixeirarebeca@yahoo.com.br', '43926217485', './Assets/avatar5.jpg'),
	('12', 'Carlos Eduardo da Mata', 'isabelly63@yahoo.com.br', '43975819828', './Assets/avatar1.jpg'),
	('13', 'Agatha Barros', 'rafaela17@ig.com.br', '43942263408', './Assets/avatar2.jpg'),
	('14', 'Calebe Oliveira', 'felipe91@yahoo.com.br', '43980446886', './Assets/avatar3.jpg'),
	('15', 'Paulo Carvalho', 'araujoryan@hotmail.com', '43921768809', './Assets/avatar3.jpg'),
	('16', 'Maitê Lima', 'umoreira@yahoo.com.br', '43987471439', './Assets/avatar2.jpg'),
	('17', 'Valentina Araújo', 'rochaisabelly@bol.com.br', '43961627155', './Assets/avatar5.jpg'),
	('18', 'Isadora Almeida', 'stellasales@bol.com.br', '43996296426', './Assets/avatar3.jpg'),
	('19', 'Lavínia Nunes', 'larissa88@uol.com.br', '43951686775', './Assets/avatar4.jpg'),
	('20', 'Yago Monteiro', 'alicia10@yahoo.com.br', '43943355751', './Assets/avatar4.jpg'),
	('21', 'Fernando Monteiro', 'nda-mota@gmail.com', '43980053834', './Assets/avatar1.jpg'),
	('22', 'João Lucas Fernandes', 'fernandonascimento@ig.com.br', '43976971621', './Assets/avatar3.jpg'),
	('23', 'Isabelly Cavalcanti', 'fogacafernanda@uol.com.br', '43998056057', './Assets/avatar3.jpg'),
	('24', 'Maria Luiza Cunha', 'da-luzlucas-gabriel@bol.com.br', '43971918501', './Assets/avatar6.jpg'),
	('25', 'Milena Martins', 'novaesmarina@yahoo.com.br', '43922995368', './Assets/avatar4.jpg'),
	('26', 'Joana Alves', 'emanuel79@gmail.com', '43937741566', './Assets/avatar1.jpg'),
	('27', 'Igor Viana', 'thomasalves@uol.com.br', '43993388446', './Assets/avatar4.jpg'),
	('28', 'Mirella Lopes', 'salesmaria-clara@hotmail.com', '43932266811', './Assets/avatar3.jpg'),
	('29', 'Rebeca Santos', 'luccaoliveira@bol.com.br', '43940374886', './Assets/avatar6.jpg'),
	('30', 'Thales Viana', 'ceciliacastro@bol.com.br', '43973164023', './Assets/avatar2.jpg'),
	('31', 'Luna Moura', 'enzocunha@uol.com.br', '43992508203', './Assets/avatar2.jpg'),
	('32', 'Ian Peixoto', 'arthurda-mata@hotmail.com', '43999206254', './Assets/avatar5.jpg'),
	('33', 'Heitor Moraes', 'benjaminda-rosa@bol.com.br', '43929823278', './Assets/avatar6.jpg'),
	('34', 'Brenda Novaes', 'isaac41@ig.com.br', '43991634863', './Assets/avatar5.jpg'),
	('35', 'Letícia Dias', 'ana78@uol.com.br', '43944275846', './Assets/avatar2.jpg'),
	('36', 'Maria Luiza Araújo', 'jfarias@uol.com.br', '43971496163', './Assets/avatar1.jpg'),
	('37', 'Helena Gomes', 'dfarias@bol.com.br', '43973145752', './Assets/avatar6.jpg'),
	('38', 'Alícia Silveira', 'otavio69@gmail.com', '43952385273', './Assets/avatar1.jpg'),
	('39', 'Alexandre Freitas', 'maria-clara80@uol.com.br', '43932436035', './Assets/avatar5.jpg'),
	('40', 'Nathan das Neves', 'guilherme01@gmail.com', '43983290028', './Assets/avatar3.jpg'),
	('41', 'Cecília Vieira', 'franciscogoncalves@hotmail.com', '43924859108', './Assets/avatar6.jpg'),
	('42', 'Clara Mendes', 'sdas-neves@ig.com.br', '43941726667', './Assets/avatar6.jpg'),
	('43', 'Maria da Costa', 'cavalcantiisaac@yahoo.com.br', '43934905538', './Assets/avatar6.jpg'),
	('44', 'Anthony Alves', 'marcelaviana@bol.com.br', '43989601100', './Assets/avatar1.jpg'),
	('45', 'Enzo Gabriel Carvalho', 'maria-luiza12@ig.com.br', '43912145213', './Assets/avatar1.jpg'),
	('46', 'Luigi Castro', 'lopesemilly@bol.com.br', '43957157999', './Assets/avatar4.jpg'),
	('47', 'Luigi Dias', 'qnunes@uol.com.br', '43952465048', './Assets/avatar1.jpg'),
	('48', 'Rafaela Fogaça', 'pedromonteiro@ig.com.br', '43910260248', './Assets/avatar6.jpg'),
	('49', 'Stella da Mata', 'carolineporto@hotmail.com', '43933960481', './Assets/avatar4.jpg'),
	('50', 'Emanuelly da Cruz', 'salesbrenda@gmail.com', '43966763131', './Assets/avatar6.jpg'),
	('51', 'Pedro Lopes', 'maria-ceciliasantos@uol.com.br', '43988825043', './Assets/avatar6.jpg'),
	('52', 'Laura Costela', 'ramosenrico@gmail.com', '43933580797', './Assets/avatar4.jpg'),
	('53', 'Milena Ramos', 'qpereira@bol.com.br', '43911381884', './Assets/avatar4.jpg'),
	('54', 'Sabrina Viana', 'esthernascimento@gmail.com', '43938658720', './Assets/avatar3.jpg'),
	('55', 'Diogo Peixoto', 'dteixeira@hotmail.com', '43962899798', './Assets/avatar2.jpg'),
	('56', 'Sabrina Cavalcanti', 'calebeporto@bol.com.br', '43922259651', './Assets/avatar1.jpg'),
	('57', 'Cauã da Mata', 'barbaranascimento@uol.com.br', '43921842144', './Assets/avatar5.jpg'),
	('58', 'Renan Carvalho', 'alicia54@uol.com.br', '43945392386', './Assets/avatar2.jpg'),
	('59', 'Ana Clara Araújo', 'wcarvalho@hotmail.com', '43989241789', './Assets/avatar6.jpg'),
	('60', 'Benjamin Ferreira', 'carvalhoana-julia@gmail.com', '43983381734', './Assets/avatar6.jpg'),
	('61', 'Fernanda Rodrigues', 'mnunes@bol.com.br', '43988210298', './Assets/avatar4.jpg'),
	('62', 'Clarice Aragão', 'marcela10@ig.com.br', '43937713158', './Assets/avatar1.jpg'),
	('63', 'Sabrina Ramos', 'zteixeira@uol.com.br', '43964950821', './Assets/avatar5.jpg'),
	('64', 'Vitória Araújo', 'da-rosabrenda@hotmail.com', '43929237868', './Assets/avatar4.jpg'),
	('65', 'Valentina Santos', 'joanacarvalho@yahoo.com.br', '43972242191', './Assets/avatar4.jpg'),
	('66', 'Evelyn Fogaça', 'emanuelly65@hotmail.com', '43987701875', './Assets/avatar6.jpg'),
	('67', 'João Lucas da Mota', 'davi-luiz87@yahoo.com.br', '43925737758', './Assets/avatar6.jpg'),
	('68', 'Luiz Fernando da Cunha', 'rochajoaquim@yahoo.com.br', '43960224910', './Assets/avatar6.jpg'),
	('69', 'Ana Laura da Cunha', 'luiz-henriqueda-costa@gmail.com', '43960502979', './Assets/avatar2.jpg'),
	('70', 'Luiz Gustavo Nogueira', 'olivia67@hotmail.com', '43968640728', './Assets/avatar6.jpg'),
	('71', 'Catarina Caldeira', 'gfogaca@uol.com.br', '43979009839', './Assets/avatar2.jpg'),
	('72', 'Benjamin Fernandes', 'livia17@ig.com.br', '43924755265', './Assets/avatar5.jpg'),
	('73', 'Enzo Gabriel Pires', 'emanuelly91@uol.com.br', '43979950333', './Assets/avatar4.jpg'),
	('74', 'Raquel Sales', 'clarice58@ig.com.br', '43969644385', './Assets/avatar6.jpg'),
	('75', 'Cauã Araújo', 'das-nevesbryan@hotmail.com', '43919483523', './Assets/avatar2.jpg'),
	('76', 'Sofia da Conceição', 'larissa57@uol.com.br', '43937873893', './Assets/avatar5.jpg'),
	('77', 'Miguel Nunes', 'danielaramos@uol.com.br', '43974037280', './Assets/avatar1.jpg'),
	('78', 'Guilherme Costela', 'manuelaribeiro@bol.com.br', '43983703535', './Assets/avatar1.jpg'),
	('79', 'Gabriel Barros', 'helenada-rocha@hotmail.com', '43950945691', './Assets/avatar2.jpg'),
	('80', 'Nathan Araújo', 'xoliveira@uol.com.br', '43976748864', './Assets/avatar6.jpg'),
	('81', 'Thiago da Rocha', 'luanada-rocha@uol.com.br', '43940150886', './Assets/avatar4.jpg'),
	('82', 'Luiz Miguel Araújo', 'bramos@ig.com.br', '43996992518', './Assets/avatar3.jpg'),
	('83', 'Pedro Henrique da Mata', 'agatha17@ig.com.br', '43959777165', './Assets/avatar2.jpg'),
	('84', 'Maysa Pires', 'lsilveira@yahoo.com.br', '43967468400', './Assets/avatar1.jpg'),
	('85', 'Henrique Moreira', 'francisco93@bol.com.br', '43999038330', './Assets/avatar6.jpg'),
	('86', 'Vitor Nunes', 'lmonteiro@ig.com.br', '43921608863', './Assets/avatar1.jpg'),
	('87', 'Lavínia da Costa', 'cardosoryan@yahoo.com.br', '43962019130', './Assets/avatar3.jpg'),
	('88', 'Samuel da Cunha', 'dferreira@bol.com.br', '43997359536', './Assets/avatar4.jpg'),
	('89', 'Lorena Gonçalves', 'uazevedo@yahoo.com.br', '43947606996', './Assets/avatar1.jpg'),
	('90', 'Ana Carolina da Cunha', 'almeidamaria-fernanda@gmail.com', '43961139237', './Assets/avatar1.jpg'),
	('91', 'Ana Laura Teixeira', 'stephanymoreira@gmail.com', '43999002276', './Assets/avatar2.jpg'),
	('92', 'Theo Pereira', 'augusto21@bol.com.br', '43926191321', './Assets/avatar3.jpg'),
	('93', 'Bernardo Moraes', 'claricearagao@uol.com.br', '43963962499', './Assets/avatar6.jpg'),
	('94', 'Calebe Martins', 'ana76@bol.com.br', '43943989804', './Assets/avatar1.jpg'),
	('95', 'Anthony Peixoto', 'gustavo-henrique30@uol.com.br', '43935570665', './Assets/avatar5.jpg'),
	('96', 'Luigi da Luz', 'noahcorreia@ig.com.br', '43982857708', './Assets/avatar6.jpg'),
	('97', 'Enzo Sales', 'marcela92@yahoo.com.br', '43973475071', './Assets/avatar1.jpg'),
	('98', 'Larissa Barros', 'danilo58@ig.com.br', '43978588353', './Assets/avatar3.jpg'),
	('99', 'Sofia Pires', 'joao-miguelnogueira@yahoo.com.br', '43990798835', './Assets/avatar5.jpg'),
	('100', 'Augusto Oliveira', 'gabriela21@uol.com.br', '43912636990', './Assets/avatar2.jpg'),
	('101', 'Antônio Rezende', 'nathanda-cruz@gmail.com', '43997135032', './Assets/avatar1.jpg'),
	('102', 'Amanda Oliveira', 'gustavo40@ig.com.br', '43968492272', './Assets/avatar2.jpg'),
	('103', 'Marcela da Rocha', 'samuelteixeira@bol.com.br', '43966321054', './Assets/avatar2.jpg'),
	('104', 'Bruna Costela', 'moreiraantonio@gmail.com', '43982054617', './Assets/avatar4.jpg'),
	('105', 'Luiz Gustavo Silva', 'beatriz67@hotmail.com', '43961471770', './Assets/avatar5.jpg'),
	('106', 'Lucas Gabriel da Rosa', 'almeidaemanuel@hotmail.com', '43916943539', './Assets/avatar5.jpg'),
	('107', 'Pedro Lucas Jesus', 'livia06@hotmail.com', '43958897487', './Assets/avatar3.jpg'),
	('108', 'Kamilly Cunha', 'rebecaporto@bol.com.br', '43911151370', './Assets/avatar3.jpg'),
	('109', 'Juan Martins', 'leandro13@ig.com.br', '43974984883', './Assets/avatar3.jpg'),
	('110', 'Maria Alice Souza', 'melissaazevedo@hotmail.com', '43993574130', './Assets/avatar4.jpg'),
	('111', 'Lara Santos', 'pauloduarte@yahoo.com.br', '43956304393', './Assets/avatar3.jpg'),
	('112', 'Fernando Pires', 'gabrielacastro@uol.com.br', '43959854654', './Assets/avatar1.jpg'),
	('113', 'Isis Santos', 'blima@ig.com.br', '43967281950', './Assets/avatar1.jpg'),
	('114', 'Camila Pinto', 'xduarte@yahoo.com.br', '43921516937', './Assets/avatar4.jpg'),
	('115', 'Maria Clara Freitas', 'da-motamarina@hotmail.com', '43970745124', './Assets/avatar2.jpg'),
	('116', 'Brenda Martins', 'camila16@uol.com.br', '43964943838', './Assets/avatar5.jpg'),
	('117', 'Pedro Henrique Santos', 'juansouza@uol.com.br', '43952046216', './Assets/avatar2.jpg'),
	('118', 'Luiz Gustavo Cardoso', 'da-cruzaugusto@ig.com.br', '43942428323', './Assets/avatar3.jpg'),
	('119', 'Maria Vitória Silveira', 'sophia58@bol.com.br', '43959797294', './Assets/avatar3.jpg'),
	('120', 'Maria Cecília Melo', 'cunhaluiz-henrique@gmail.com', '43927077989', './Assets/avatar4.jpg'),
	('121', 'Davi Lucca da Mata', 'zmoreira@uol.com.br', '43991749719', './Assets/avatar5.jpg'),
	('122', 'Cauã Viana', 'vicente11@uol.com.br', '43912659858', './Assets/avatar2.jpg'),
	('123', 'Davi Lucca Moreira', 'guilhermebarbosa@yahoo.com.br', '43951941462', './Assets/avatar5.jpg'),
	('124', 'Levi Dias', 'cardosocaua@gmail.com', '43981140491', './Assets/avatar3.jpg'),
	('125', 'Larissa Mendes', 'maria-clarabarros@bol.com.br', '43992153140', './Assets/avatar2.jpg'),
	('126', 'Esther Ramos', 'aragaofrancisco@ig.com.br', '43960890179', './Assets/avatar6.jpg'),
	('127', 'Luana Barros', 'joaquimcorreia@uol.com.br', '43996094147', './Assets/avatar4.jpg'),
	('128', 'Lívia Farias', 'piresgabriel@gmail.com', '43910902812', './Assets/avatar6.jpg'),
	('129', 'Caroline Nascimento', 'luiz-fernando79@bol.com.br', '43924905953', './Assets/avatar6.jpg'),
	('130', 'Helena Nogueira', 'crocha@uol.com.br', '43945472187', './Assets/avatar2.jpg'),
	('131', 'Murilo da Rocha', 'alexandre56@yahoo.com.br', '43923571849', './Assets/avatar4.jpg'),
	('132', 'Francisco Barros', 'cardosonathan@uol.com.br', '43995741346', './Assets/avatar4.jpg'),
	('133', 'Enzo da Costa', 'daniloaraujo@uol.com.br', '43945052918', './Assets/avatar1.jpg'),
	('134', 'João Guilherme Lima', 'vianathales@yahoo.com.br', '43981461057', './Assets/avatar1.jpg'),
	('135', 'Pedro Henrique Costa', 'hcardoso@uol.com.br', '43990960676', './Assets/avatar4.jpg'),
	('136', 'Matheus Lima', 'umoraes@hotmail.com', '43961513512', './Assets/avatar3.jpg'),
	('137', 'Yuri Carvalho', 'wcastro@hotmail.com', '43982349246', './Assets/avatar2.jpg'),
	('138', 'Davi da Mota', 'cavalcantiisabelly@gmail.com', '43966267634', './Assets/avatar4.jpg'),
	('139', 'Julia Silva', 'rnovaes@bol.com.br', '43912859715', './Assets/avatar3.jpg'),
	('140', 'Fernanda Duarte', 'ocardoso@yahoo.com.br', '43928695205', './Assets/avatar4.jpg'),
	('141', 'Stella da Mata', 'vitor-gabrielnunes@hotmail.com', '43914367092', './Assets/avatar3.jpg'),
	('142', 'Vitória Fernandes', 'aragaoalexandre@ig.com.br', '43969425598', './Assets/avatar6.jpg'),
	('143', 'Antônio da Cunha', 'caldeirasophia@bol.com.br', '43963509652', './Assets/avatar4.jpg'),
	('144', 'Luna Pereira', 'mendesagatha@bol.com.br', '43922950503', './Assets/avatar6.jpg'),
	('145', 'Ana Carolina Ferreira', 'cnogueira@uol.com.br', '43992492083', './Assets/avatar5.jpg'),
	('146', 'Beatriz Jesus', 'gmoura@hotmail.com', '43989680821', './Assets/avatar2.jpg'),
	('147', 'Catarina Gomes', 'kmartins@ig.com.br', '43930577708', './Assets/avatar2.jpg'),
	('148', 'Olivia Mendes', 'leticiaribeiro@ig.com.br', '43962176535', './Assets/avatar1.jpg'),
	('149', 'Ana Julia da Rocha', 'levi26@yahoo.com.br', '43962047848', './Assets/avatar6.jpg'),
	('150', 'Ana Sophia Nascimento', 'vitor-gabrielnogueira@yahoo.com.br', '43990677087', './Assets/avatar6.jpg'),
	('151', 'Otávio Silveira', 'rodriguesdavi-lucca@bol.com.br', '43941100263', './Assets/avatar4.jpg'),
	('152', 'Sofia Santos', 'souzaana-carolina@bol.com.br', '43918312351', './Assets/avatar3.jpg'),
	('153', 'Davi Lucca Teixeira', 'rcavalcanti@bol.com.br', '43910990552', './Assets/avatar1.jpg'),
	('154', 'Kevin da Costa', 'nascimentoluiz-otavio@hotmail.com', '43930846107', './Assets/avatar6.jpg'),
	('155', 'Leonardo Freitas', 'fernandesmiguel@bol.com.br', '43994711356', './Assets/avatar4.jpg'),
	('156', 'Ana Lívia Correia', 'maysadias@yahoo.com.br', '43979737086', './Assets/avatar4.jpg'),
	('157', 'Isabelly Pinto', 'leticiacarvalho@ig.com.br', '43990376902', './Assets/avatar3.jpg'),
	('158', 'Isabelly Nascimento', 'acaldeira@ig.com.br', '43939271598', './Assets/avatar5.jpg'),
	('159', 'Alana Costela', 'psouza@ig.com.br', '43935211953', './Assets/avatar2.jpg'),
	('160', 'Isabel da Mota', 'vianaana-clara@bol.com.br', '43942501568', './Assets/avatar5.jpg'),
	('161', 'Emilly Peixoto', 'catarinabarbosa@bol.com.br', '43943226739', './Assets/avatar6.jpg'),
	('162', 'Renan Freitas', 'nina46@gmail.com', '43926576756', './Assets/avatar6.jpg'),
	('163', 'Antônio Barros', 'enzo12@hotmail.com', '43911852838', './Assets/avatar4.jpg'),
	('164', 'Diego Cavalcanti', 'thiagomendes@hotmail.com', '43917404500', './Assets/avatar4.jpg'),
	('165', 'Daniel Teixeira', 'lbarros@yahoo.com.br', '43944576952', './Assets/avatar4.jpg'),
	('166', 'Alice Cardoso', 'goncalvesmirella@gmail.com', '43986820015', './Assets/avatar3.jpg'),
	('167', 'Maitê Aragão', 'moraesbenicio@yahoo.com.br', '43990817208', './Assets/avatar4.jpg'),
	('168', 'Vinicius Ramos', 'pcunha@uol.com.br', '43959131350', './Assets/avatar3.jpg'),
	('169', 'Heitor Aragão', 'pedro-henrique92@bol.com.br', '43989767804', './Assets/avatar3.jpg'),
	('170', 'Valentina Peixoto', 'das-nevesmaria-fernanda@ig.com.br', '43939284884', './Assets/avatar1.jpg'),
	('171', 'Sarah Correia', 'ana-luiza55@gmail.com', '43912010453', './Assets/avatar3.jpg'),
	('172', 'Theo Nunes', 'sofia35@bol.com.br', '43913089091', './Assets/avatar2.jpg'),
	('173', 'Maria Eduarda Duarte', 'mouralarissa@hotmail.com', '43937404343', './Assets/avatar6.jpg'),
	('174', 'Ana Julia Almeida', 'vitor40@hotmail.com', '43968460367', './Assets/avatar5.jpg'),
	('175', 'Pietra Nunes', 'fogacacarolina@ig.com.br', '43993952273', './Assets/avatar1.jpg'),
	('176', 'Melissa da Luz', 'maria-eduarda97@uol.com.br', '43994999216', './Assets/avatar3.jpg'),
	('177', 'Diogo Souza', 'ana-clararodrigues@uol.com.br', '43929465421', './Assets/avatar2.jpg'),
	('178', 'Antônio Araújo', 'santosemanuella@bol.com.br', '43951223778', './Assets/avatar1.jpg'),
	('179', 'Luna Moreira', 'gomesdiego@hotmail.com', '43925669243', './Assets/avatar6.jpg'),
	('180', 'Agatha Pereira', 'agatha69@ig.com.br', '43945314192', './Assets/avatar2.jpg'),
	('181', 'Alana Cunha', 'mendesgustavo-henrique@ig.com.br', '43940455077', './Assets/avatar2.jpg'),
	('182', 'Enzo Gabriel Freitas', 'nicole57@gmail.com', '43983612393', './Assets/avatar2.jpg'),
	('183', 'Lívia da Conceição', 'pda-rosa@uol.com.br', '43944704173', './Assets/avatar4.jpg'),
	('184', 'Lorena Moura', 'benjaminda-cruz@uol.com.br', '43964906452', './Assets/avatar4.jpg'),
	('185', 'Letícia Barros', 'ynovaes@gmail.com', '43929778155', './Assets/avatar6.jpg'),
	('186', 'Heloísa Souza', 'da-rosaemanuella@hotmail.com', '43958072121', './Assets/avatar1.jpg'),
	('187', 'Gabrielly Porto', 'davisilveira@uol.com.br', '43933619536', './Assets/avatar1.jpg'),
	('188', 'Davi Luiz Fogaça', 'luanarezende@yahoo.com.br', '43932237652', './Assets/avatar6.jpg'),
	('189', 'Nicolas Sales', 'lorenzopinto@uol.com.br', '43958084790', './Assets/avatar6.jpg'),
	('190', 'Diogo Moreira', 'luiz-otaviocarvalho@hotmail.com', '43933264281', './Assets/avatar3.jpg'),
	('191', 'Thomas Teixeira', 'catarina91@hotmail.com', '43936719157', './Assets/avatar6.jpg'),
	('192', 'Yuri da Cruz', 'ryan78@yahoo.com.br', '43944037252', './Assets/avatar1.jpg'),
	('193', 'Maria Julia Silva', 'matheus61@ig.com.br', '43981533777', './Assets/avatar2.jpg'),
	('194', 'Vitor Gabriel das Neves', 'erick57@gmail.com', '43939815234', './Assets/avatar1.jpg'),
	('195', 'Maria Julia Teixeira', 'alexiafreitas@yahoo.com.br', '43939502543', './Assets/avatar4.jpg'),
	('196', 'Pedro Miguel Teixeira', 'costelapedro@yahoo.com.br', '43925299980', './Assets/avatar3.jpg'),
	('197', 'Daniel Rocha', 'sarahrocha@ig.com.br', '43948832763', './Assets/avatar6.jpg'),
	('198', 'Mariana Caldeira', 'leandroaragao@uol.com.br', '43993651052', './Assets/avatar4.jpg'),
	('199', 'Fernando Ribeiro', 'mirellacardoso@bol.com.br', '43958114100', './Assets/avatar4.jpg'),
	('200', 'Davi Lucas Melo', 'sda-cunha@bol.com.br', '43955950428', './Assets/avatar4.jpg');

INSERT INTO prestador (prestador_id, nome, email, fone, especialidade, avatar) VALUES
	('1', 'Ana Clara Fernandes', 'cardosomilena@gmail.com', '43919787507', 'Pintura', './Assets/colab7.jpg'),
	('2', 'Calebe Gonçalves', 'cauemelo@yahoo.com.br', '43968478162', 'Hidráulica', './Assets/Colab1.jpg'),
	('3', 'Cauê Lopes', 'ana-clarapinto@bol.com.br', '43986714076', 'Pintura', './Assets/colab4.jpg'),
	('4', 'Vitor Santos', 'ida-rocha@gmail.com', '43935360966', 'Alvenaria e infraestrutra', './Assets/colab8.jpg'),
	('5', 'João Pedro Cavalcanti', 'silvamilena@gmail.com', '43920072939', 'Hidráulica', './Assets/colab4.jpg'),
	('6', 'Daniela Fogaça', 'pteixeira@uol.com.br', '43967547892', 'Hidráulica', './Assets/colab6.jpg'),
	('7', 'Emanuelly Martins', 'joao-gabriel93@ig.com.br', '43997771995', 'Elétrica', './Assets/colab7.jpg'),
	('8', 'Maria Alice Rodrigues', 'rezendeemanuella@hotmail.com', '43922632439', 'Pintura', './Assets/colab3.jpg'),
	('9', 'Amanda da Mata', 'fernandaoliveira@hotmail.com', '43958880286', 'Carpintaria', './Assets/colab6.jpg'),
	('10', 'Ana Clara Santos', 'dcardoso@ig.com.br', '43957977364', 'Elétrica', './Assets/colab2.jpg'),
	('11', 'Clarice da Mata', 'diasthiago@hotmail.com', '43998258513', 'Pintura', './Assets/colab3.jpg'),
	('12', 'João Guilherme Ferreira', 'lcostela@bol.com.br', '43929943810', 'Pequenos Reparos', './Assets/colab5.jpg'),
	('13', 'Bárbara da Mota', 'da-motaenzo@yahoo.com.br', '43942325716', 'Hidráulica', './Assets/colab7.jpg'),
	('14', 'Melissa Alves', 'vporto@hotmail.com', '43983546328', 'Pintura', './Assets/colab2.jpg'),
	('15', 'Fernando Monteiro', 'rafaelateixeira@uol.com.br', '43915400462', 'Hidráulica', './Assets/Colab1.jpg'),
	('16', 'Ana Beatriz Martins', 'felipe02@uol.com.br', '43953059476', 'Pequenos Reparos', './Assets/colab6.jpg'),
	('17', 'Davi Duarte', 'xbarros@ig.com.br', '43928514369', 'Acabamentos', './Assets/colab4.jpg'),
	('18', 'Alice da Conceição', 'sophie93@yahoo.com.br', '43982106650', 'Alvenaria e infraestrutra', './Assets/colab7.jpg'),
	('19', 'Benício Cardoso', 'qmoraes@gmail.com', '43941806626', 'Carpintaria', './Assets/colab5.jpg'),
	('20', 'Laura Teixeira', 'alicia92@gmail.com', '43917017639', 'Hidráulica', './Assets/colab3.jpg'),
	('21', 'Ana Beatriz Silva', 'luiz-miguelbarbosa@gmail.com', '43956940375', 'Acabamentos', './Assets/colab2.jpg'),
	('22', 'Luiz Henrique Fogaça', 'peixotoenzo-gabriel@gmail.com', '43969266893', 'Acabamentos', './Assets/colab8.jpg'),
	('23', 'Laura Pinto', 'fernandesluiza@gmail.com', '43976253973', 'Hidráulica', './Assets/colab3.jpg'),
	('24', 'Enrico Almeida', 'camila00@uol.com.br', '43911702064', 'Pintura', './Assets/Colab1.jpg'),
	('25', 'Cecília Porto', 'beniciosales@bol.com.br', '43964705161', 'Pequenos Reparos', './Assets/colab3.jpg'),
	('26', 'Ana Alves', 'luiz-henriquerocha@ig.com.br', '43927587663', 'Hidráulica', './Assets/colab2.jpg'),
	('27', 'Henrique Moreira', 'marcelo61@ig.com.br', '43920697847', 'Pequenos Reparos', './Assets/colab5.jpg'),
	('28', 'Thales Moraes', 'marianunes@bol.com.br', '43921210255', 'Carpintaria', './Assets/Colab1.jpg'),
	('29', 'Kevin das Neves', 'ysilva@yahoo.com.br', '43917410210', 'Hidráulica', './Assets/colab4.jpg'),
	('30', 'Vinicius da Cruz', 'da-cruzelisa@uol.com.br', '43942578854', 'Hidráulica', './Assets/colab8.jpg');

INSERT INTO avaliacao (avaliacao_id, avaliador_id, avaliado_id, nota_avaliacao, avaliacao_texto) VALUES
	('1', '6', '20', '5', 'Equipe altamente profissional! Cumpriram o prazo e o resultado da reforma da minha cozinha ficou incrível. Recomendo totalmente.'),
	('2', '182', '2', '3', 'Contratei-os para uma reforma de banheiro e fiquei muito satisfeito com o resultado final. Ótimo trabalho e atenção aos detalhes.'),
	('3', '136', '21', '4', '"Excelente serviço de construção! Desde o planejamento até a execução, tudo foi feito com cuidado e competência. Muito obrigado!"'),
	('4', '103', '28', '4', 'Profissionais pontuais e qualificados. Transformaram minha área externa de forma surpreendente. Recomendo!'),
	('5', '129', '21', '1', 'A reforma do meu escritório foi concluída no prazo e com excelente qualidade. Equipe comprometida e eficiente.'),
	('6', '66', '13', '2', 'Contratei-os para uma pequena reforma em casa e fiquei impressionado com o profissionalismo e a dedicação da equipe. Recomendo de olhos fechados!'),
	('7', '37', '18', '1', 'Serviço de construção excepcional! A equipe foi além das expectativas e entregou um trabalho de alta qualidade dentro do prazo estipulado.'),
	('8', '154', '1', '3', 'Estou muito contente com a reforma da minha sala. Profissionais atenciosos e habilidosos. Recomendo a todos!'),
	('9', '159', '3', '4', 'Equipe extremamente competente na execução da reforma da minha varanda. Preço justo e resultado final incrível!'),
	('10', '127', '5', '2', 'Serviço de construção impecável! Profissionais qualificados e comprometidos. Superaram minhas expectativas.'),
	('11', '68', '29', '4', 'Contratei-os para uma reforma em casa e o resultado foi além do esperado. Profissionais dedicados e serviço de alta qualidade.'),
	('12', '19', '13', '1', 'A empresa demonstrou grande expertise na reforma do meu apartamento. Pontualidade e comprometimento foram marcas do serviço prestado.'),
	('13', '103', '5', '4', 'Profissionais responsáveis e capacitados. A reforma do meu escritório foi realizada com eficiência e qualidade.'),
	('14', '10', '15', '3', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('15', '26', '1', '4', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('16', '68', '11', '3', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('17', '87', '3', '2', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('18', '181', '8', '2', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('19', '152', '17', '5', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('20', '169', '10', '2', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('21', '126', '21', '5', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('22', '68', '28', '1', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('23', '122', '22', '4', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('24', '143', '17', '2', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('25', '143', '27', '4', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('26', '83', '10', '2', '"O serviço de construção foi satisfatório, porém, a falta de sugestões criativas para otimização do espaço foi notável. Mais proatividade seria interessante."'),
	('27', '161', '9', '2', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('28', '77', '14', '5', '"Apesar do bom serviço na reforma da área externa, a comunicação sobre mudanças no projeto foi pouco eficiente. Melhor articulação entre cliente e equipe seria vantajosa."'),
	('29', '57', '25', '3', '"A reforma da minha varanda teve um resultado satisfatório, mas a falta de comprometimento com prazos foi um problema. Maior responsabilidade na gestão do tempo é crucial."'),
	('30', '54', '25', '5', '"Houve um bom esforço na execução da construção, mas a falta de supervisão levou a alguns erros na fase inicial. Sugiro mais controle de qualidade desde o início do projeto."'),
	('31', '185', '18', '4', '"A equipe foi atenciosa na reforma do meu apartamento, no entanto, a falta de cuidado na proteção de áreas adjacentes durante a obra foi notável. Maior zelo é necessário."'),
	('32', '62', '13', '4', '"Contratei-os para uma reforma em casa. Apesar da qualidade do serviço, houve falta de transparência em relação aos materiais utilizados. Maior clareza seria positiva."'),
	('33', '56', '27', '4', '"O serviço de construção atendeu às expectativas, mas a ausência de um plano de contingência para imprevistos prejudicou o andamento do projeto. Melhor preparação é necessária."'),
	('34', '92', '6', '1', '"A equipe foi competente na reforma do meu escritório, no entanto, houve dificuldades na comunicação sobre alterações no projeto. Melhorias na comunicação são essenciais."'),
	('35', '83', '10', '4', '"A reforma do meu banheiro teve um bom resultado final, porém, a falta de acompanhamento regular do progresso gerou incertezas. Recomendo maior feedback ao cliente."'),
	('36', '29', '6', '5', '"Embora tenham entregado a construção no prazo, houve problemas com a qualidade de alguns materiais utilizados. Sugiro maior atenção à seleção de materiais de melhor qualidade."'),
	('37', '32', '15', '4', '"A equipe foi comprometida na reforma da minha cozinha, mas alguns detalhes de acabamento foram negligenciados. Melhor atenção aos detalhes é fundamental."'),
	('38', '150', '14', '4', '"O serviço de construção foi satisfatório, porém, houve falta de cuidado na proteção de áreas adjacentes durante a obra. Maior zelo com o ambiente é necessário."'),
	('39', '97', '11', '4', '"Apesar do resultado final da reforma ter sido positivo, a falta de flexibilidade para ajustes no projeto foi um obstáculo. Sugiro maior adaptabilidade"'),
	('40', '115', '21', '3', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('41', '161', '19', '5', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('42', '65', '17', '2', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('43', '183', '4', '2', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('44', '12', '1', '5', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('45', '127', '23', '1', '"O serviço de construção foi satisfatório, mas houve divergências no orçamento inicial e final. Recomendo mais clareza nos custos extras durante o projeto."'),
	('46', '118', '1', '5', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('47', '179', '18', '3', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('48', '152', '12', '3', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('49', '111', '2', '4', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('50', '135', '14', '1', '"A equipe foi pontual e comprometida na reforma do meu banheiro, porém, seria vantajoso oferecer opções mais sustentáveis de materiais para escolha dos clientes, alinhando-se às tendências ambientais."'),
	('51', '122', '19', '1', '"O serviço de construção foi bem executado, no entanto, seria benéfico ter mais disponibilidade para reuniões intermediárias durante o projeto, para alinhar expectativas e ajustar detalhes conforme necessário."'),
	('52', '102', '25', '1', '"A reforma da minha cozinha teve um ótimo resultado, mas seria interessante oferecer um portfólio mais diversificado de designs e estilos para inspirar os clientes na concepção do projeto."'),
	('53', '30', '11', '5', '"Embora a equipe tenha sido atenciosa durante a construção, seria útil ter um sistema de comunicação mais eficiente para que o cliente possa acompanhar o progresso em tempo real, garantindo maior transparência."'),
	('54', '152', '10', '4', '"O serviço prestado na reforma do meu escritório foi de qualidade, porém, seria valioso oferecer pacotes ou descontos para projetos maiores, incentivando os clientes a realizarem mais melhorias de uma vez."'),
	('55', '156', '25', '3', '"Houve dedicação na construção, mas seria útil oferecer um serviço pós-obra, como um manual de manutenção ou garantia estendida, para garantir a durabilidade do trabalho realizado."'),
	('56', '40', '29', '3', '"A equipe foi diligente na reforma da minha casa, no entanto, seria interessante oferecer opções de financiamento ou parcelamento, tornando o serviço mais acessível a diferentes perfis de clientes."'),
	('57', '179', '26', '1', '"Apesar da qualidade do serviço, seria valioso disponibilizar um canal de feedback estruturado para os clientes expressarem suas necessidades e sugestões durante o processo de reforma."'),
	('58', '52', '23', '3', '"O resultado da construção foi satisfatório, porém, seria benéfico oferecer um serviço de consultoria adicional para otimização de espaços, agregando ainda mais valor ao projeto."'),
	('59', '41', '27', '5', '"A equipe foi comprometida na reforma do meu banheiro, mas seria vantajoso ter um acompanhamento pós-obra para garantir que todos os detalhes foram finalizados conforme acordado."'),
	('60', '130', '29', '5', '"Apesar da qualidade do serviço, seria valioso disponibilizar um canal de feedback estruturado para os clientes expressarem suas necessidades e sugestões durante o processo de reforma."'),
	('61', '39', '13', '3', '"O resultado da construção foi satisfatório, porém, seria benéfico oferecer um serviço de consultoria adicional para otimização de espaços, agregando ainda mais valor ao projeto."'),
	('62', '19', '12', '3', '"A equipe foi comprometida na reforma do meu banheiro, mas seria vantajoso ter um acompanhamento pós-obra para garantir que todos os detalhes foram finalizados conforme acordado."'),
	('63', '149', '2', '2', '"Embora a comunicação tenha sido clara, seria útil oferecer um serviço de assistência técnica por um período após a conclusão da reforma, para resolver eventuais problemas que possam surgir."'),
	('64', '20', '26', '5', '"A qualidade do serviço foi boa, no entanto, seria valioso disponibilizar um catálogo mais amplo de fornecedores de materiais para dar mais opções aos clientes na escolha dos materiais."'),
	('65', '197', '27', '2', '"Apesar da eficiência na execução, seria interessante oferecer um serviço de gerenciamento de resíduos mais robusto, visando a sustentabilidade e o descarte responsável dos materiais utilizados."'),
	('66', '169', '11', '1', '"A equipe foi prestativa na reforma da minha cozinha, mas seria útil oferecer um programa de fidelidade ou indicação para clientes frequentes, incentivando sua fidelização."'),
	('67', '161', '22', '5', '"Embora tenham entregado dentro do prazo, seria vantajoso disponibilizar um serviço de prévia virtual do projeto, utilizando tecnologias de realidade aumentada para visualização mais precisa."'),
	('68', '74', '21', '1', '"A atenção aos detalhes foi boa, mas seria valioso oferecer um serviço de consultoria em decoração após a conclusão da reforma, para ajudar os clientes na ambientação do espaço."'),
	('69', '110', '4', '3', '"Apesar da organização, seria interessante oferecer um serviço de garantia estendida para os materiais utilizados, assegurando aos clientes uma maior tranquilidade após a conclusão da obra."'),
	('70', '35', '26', '1', '"A equipe foi comprometida na reforma do meu escritório, mas seria benéfico ter um sistema de gestão online, onde os clientes pudessem acompanhar o progresso e fazer comentários em tempo real."'),
	('71', '116', '18', '3', '"Apesar da limpeza final, seria útil oferecer um serviço de manutenção preventiva para as instalações, ajudando os clientes a prolongarem a vida útil dos novos elementos da reforma."'),
	('72', '90', '19', '1', '"A comunicação foi clara, mas seria valioso oferecer um serviço de atendimento pós-obra com um canal exclusivo para dúvidas ou emergências que possam surgir após a conclusão do projeto."'),
	('73', '45', '9', '2', 'Equipe altamente profissional! Cumpriram o prazo e o resultado da reforma da minha cozinha ficou incrível. Recomendo totalmente.'),
	('74', '57', '4', '4', 'Contratei-os para uma reforma de banheiro e fiquei muito satisfeito com o resultado final. Ótimo trabalho e atenção aos detalhes.'),
	('75', '181', '24', '5', '"Excelente serviço de construção! Desde o planejamento até a execução, tudo foi feito com cuidado e competência. Muito obrigado!"'),
	('76', '123', '2', '2', 'Profissionais pontuais e qualificados. Transformaram minha área externa de forma surpreendente. Recomendo!'),
	('77', '97', '5', '3', 'A reforma do meu escritório foi concluída no prazo e com excelente qualidade. Equipe comprometida e eficiente.'),
	('78', '105', '6', '2', 'Contratei-os para uma pequena reforma em casa e fiquei impressionado com o profissionalismo e a dedicação da equipe. Recomendo de olhos fechados!'),
	('79', '142', '19', '3', 'Serviço de construção excepcional! A equipe foi além das expectativas e entregou um trabalho de alta qualidade dentro do prazo estipulado.'),
	('80', '192', '13', '2', 'Estou muito contente com a reforma da minha sala. Profissionais atenciosos e habilidosos. Recomendo a todos!'),
	('81', '137', '26', '3', 'Equipe extremamente competente na execução da reforma da minha varanda. Preço justo e resultado final incrível!'),
	('82', '92', '6', '5', 'Serviço de construção impecável! Profissionais qualificados e comprometidos. Superaram minhas expectativas.'),
	('83', '198', '25', '3', 'Contratei-os para uma reforma em casa e o resultado foi além do esperado. Profissionais dedicados e serviço de alta qualidade.'),
	('84', '155', '23', '4', 'A empresa demonstrou grande expertise na reforma do meu apartamento. Pontualidade e comprometimento foram marcas do serviço prestado.'),
	('85', '26', '12', '2', 'Profissionais responsáveis e capacitados. A reforma do meu escritório foi realizada com eficiência e qualidade.'),
	('86', '167', '2', '2', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('87', '14', '14', '1', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('88', '102', '17', '4', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('89', '166', '11', '1', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('90', '65', '11', '1', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('91', '149', '21', '5', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('92', '63', '6', '1', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('93', '132', '21', '2', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('94', '143', '3', '5', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('95', '123', '4', '3', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('96', '183', '10', '4', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('97', '51', '23', '5', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('98', '131', '16', '2', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('99', '32', '2', '2', '"Apesar do bom serviço na reforma da área externa, a comunicação sobre mudanças no projeto foi pouco eficiente. Melhor articulação entre cliente e equipe seria vantajosa."'),
	('100', '91', '18', '1', '"A reforma da minha varanda teve um resultado satisfatório, mas a falta de comprometimento com prazos foi um problema. Maior responsabilidade na gestão do tempo é crucial."'),
	('101', '169', '28', '5', '"Houve um bom esforço na execução da construção, mas a falta de supervisão levou a alguns erros na fase inicial. Sugiro mais controle de qualidade desde o início do projeto."'),
	('102', '94', '1', '3', '"A equipe foi atenciosa na reforma do meu apartamento, no entanto, a falta de sugestões criativas para otimização do espaço foi notável. Mais proatividade seria interessante."'),
	('103', '196', '6', '2', '"Contratei-os para uma reforma em casa. Apesar da qualidade do serviço, houve falta de transparência em relação aos materiais utilizados. Maior clareza seria positiva."'),
	('104', '94', '10', '2', '"O serviço de construção atendeu às expectativas, mas a ausência de um plano de contingência para imprevistos prejudicou o andamento do projeto. Melhor preparação é necessária."'),
	('105', '84', '26', '3', '"A equipe foi competente na reforma do meu escritório, no entanto, houve dificuldades na comunicação sobre alterações no projeto. Melhorias na comunicação são essenciais."'),
	('106', '125', '29', '3', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('107', '135', '15', '4', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('108', '51', '11', '3', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('109', '112', '6', '4', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('110', '12', '25', '3', 'Equipe altamente profissional! Cumpriram o prazo e o resultado da reforma da minha cozinha ficou incrível. Recomendo totalmente.'),
	('111', '156', '20', '3', 'Contratei-os para uma reforma de banheiro e fiquei muito satisfeito com o resultado final. Ótimo trabalho e atenção aos detalhes.'),
	('112', '179', '18', '1', '"Excelente serviço de construção! Desde o planejamento até a execução, tudo foi feito com cuidado e competência. Muito obrigado!"'),
	('113', '14', '16', '5', 'Profissionais pontuais e qualificados. Transformaram minha área externa de forma surpreendente. Recomendo!'),
	('114', '19', '27', '2', 'A reforma do meu escritório foi concluída no prazo e com excelente qualidade. Equipe comprometida e eficiente.'),
	('115', '91', '12', '1', 'Contratei-os para uma pequena reforma em casa e fiquei impressionado com o profissionalismo e a dedicação da equipe. Recomendo de olhos fechados!'),
	('116', '186', '14', '2', 'Serviço de construção excepcional! A equipe foi além das expectativas e entregou um trabalho de alta qualidade dentro do prazo estipulado.'),
	('117', '163', '14', '5', 'Estou muito contente com a reforma da minha sala. Profissionais atenciosos e habilidosos. Recomendo a todos!'),
	('118', '194', '16', '4', 'Equipe extremamente competente na execução da reforma da minha varanda. Preço justo e resultado final incrível!'),
	('119', '2', '4', '4', 'Serviço de construção impecável! Profissionais qualificados e comprometidos. Superaram minhas expectativas.'),
	('120', '84', '16', '1', 'Contratei-os para uma reforma em casa e o resultado foi além do esperado. Profissionais dedicados e serviço de alta qualidade.'),
	('121', '97', '10', '5', 'A empresa demonstrou grande expertise na reforma do meu apartamento. Pontualidade e comprometimento foram marcas do serviço prestado.'),
	('122', '114', '4', '1', 'Profissionais responsáveis e capacitados. A reforma do meu escritório foi realizada com eficiência e qualidade.'),
	('123', '144', '30', '5', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('124', '146', '14', '1', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('125', '50', '2', '2', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('126', '78', '11', '4', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('127', '7', '8', '3', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('128', '31', '22', '1', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('129', '198', '13', '5', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('130', '125', '2', '4', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('131', '67', '7', '3', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('132', '21', '24', '4', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('133', '158', '10', '2', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('134', '82', '18', '2', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('135', '191', '20', '1', '"O serviço de construção foi satisfatório, porém, a falta de sugestões criativas para otimização do espaço foi notável. Mais proatividade seria interessante."'),
	('136', '96', '1', '2', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('137', '129', '9', '4', '"Apesar do bom serviço na reforma da área externa, a comunicação sobre mudanças no projeto foi pouco eficiente. Melhor articulação entre cliente e equipe seria vantajosa."'),
	('138', '72', '18', '5', '"A reforma da minha varanda teve um resultado satisfatório, mas a falta de comprometimento com prazos foi um problema. Maior responsabilidade na gestão do tempo é crucial."'),
	('139', '134', '14', '5', '"Houve um bom esforço na execução da construção, mas a falta de supervisão levou a alguns erros na fase inicial. Sugiro mais controle de qualidade desde o início do projeto."'),
	('140', '8', '9', '5', '"A equipe foi atenciosa na reforma do meu apartamento, no entanto, a falta de cuidado na proteção de áreas adjacentes durante a obra foi notável. Maior zelo é necessário."'),
	('141', '43', '6', '2', '"Contratei-os para uma reforma em casa. Apesar da qualidade do serviço, houve falta de transparência em relação aos materiais utilizados. Maior clareza seria positiva."'),
	('142', '10', '4', '5', '"O serviço de construção atendeu às expectativas, mas a ausência de um plano de contingência para imprevistos prejudicou o andamento do projeto. Melhor preparação é necessária."'),
	('143', '93', '20', '3', '"A equipe foi competente na reforma do meu escritório, no entanto, houve dificuldades na comunicação sobre alterações no projeto. Melhorias na comunicação são essenciais."'),
	('144', '155', '10', '1', '"A reforma do meu banheiro teve um bom resultado final, porém, a falta de acompanhamento regular do progresso gerou incertezas. Recomendo maior feedback ao cliente."'),
	('145', '23', '13', '3', '"Embora tenham entregado a construção no prazo, houve problemas com a qualidade de alguns materiais utilizados. Sugiro maior atenção à seleção de materiais de melhor qualidade."'),
	('146', '103', '16', '2', '"A equipe foi comprometida na reforma da minha cozinha, mas alguns detalhes de acabamento foram negligenciados. Melhor atenção aos detalhes é fundamental."'),
	('147', '27', '29', '4', '"O serviço de construção foi satisfatório, porém, houve falta de cuidado na proteção de áreas adjacentes durante a obra. Maior zelo com o ambiente é necessário."'),
	('148', '67', '4', '5', '"Apesar do resultado final da reforma ter sido positivo, a falta de flexibilidade para ajustes no projeto foi um obstáculo. Sugiro maior adaptabilidade"'),
	('149', '124', '29', '2', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('150', '123', '30', '4', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('151', '156', '9', '1', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('152', '134', '12', '2', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('153', '186', '6', '2', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('154', '164', '25', '1', '"O serviço de construção foi satisfatório, mas houve divergências no orçamento inicial e final. Recomendo mais clareza nos custos extras durante o projeto."'),
	('155', '179', '5', '2', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('156', '191', '26', '1', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('157', '18', '22', '5', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('158', '148', '2', '4', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('159', '34', '19', '2', '"A equipe foi pontual e comprometida na reforma do meu banheiro, porém, seria vantajoso oferecer opções mais sustentáveis de materiais para escolha dos clientes, alinhando-se às tendências ambientais."'),
	('160', '15', '26', '5', '"O serviço de construção foi bem executado, no entanto, seria benéfico ter mais disponibilidade para reuniões intermediárias durante o projeto, para alinhar expectativas e ajustar detalhes conforme necessário."'),
	('161', '22', '25', '4', '"A reforma da minha cozinha teve um ótimo resultado, mas seria interessante oferecer um portfólio mais diversificado de designs e estilos para inspirar os clientes na concepção do projeto."'),
	('162', '39', '12', '3', '"Embora a equipe tenha sido atenciosa durante a construção, seria útil ter um sistema de comunicação mais eficiente para que o cliente possa acompanhar o progresso em tempo real, garantindo maior transparência."'),
	('163', '163', '22', '2', '"O serviço prestado na reforma do meu escritório foi de qualidade, porém, seria valioso oferecer pacotes ou descontos para projetos maiores, incentivando os clientes a realizarem mais melhorias de uma vez."'),
	('164', '19', '8', '1', '"Houve dedicação na construção, mas seria útil oferecer um serviço pós-obra, como um manual de manutenção ou garantia estendida, para garantir a durabilidade do trabalho realizado."'),
	('165', '190', '26', '1', '"A equipe foi diligente na reforma da minha casa, no entanto, seria interessante oferecer opções de financiamento ou parcelamento, tornando o serviço mais acessível a diferentes perfis de clientes."'),
	('166', '75', '22', '2', '"Apesar da qualidade do serviço, seria valioso disponibilizar um canal de feedback estruturado para os clientes expressarem suas necessidades e sugestões durante o processo de reforma."'),
	('167', '38', '16', '4', '"O resultado da construção foi satisfatório, porém, seria benéfico oferecer um serviço de consultoria adicional para otimização de espaços, agregando ainda mais valor ao projeto."'),
	('168', '150', '19', '5', '"A equipe foi comprometida na reforma do meu banheiro, mas seria vantajoso ter um acompanhamento pós-obra para garantir que todos os detalhes foram finalizados conforme acordado."'),
	('169', '60', '13', '5', '"Apesar da qualidade do serviço, seria valioso disponibilizar um canal de feedback estruturado para os clientes expressarem suas necessidades e sugestões durante o processo de reforma."'),
	('170', '71', '27', '2', '"O resultado da construção foi satisfatório, porém, seria benéfico oferecer um serviço de consultoria adicional para otimização de espaços, agregando ainda mais valor ao projeto."'),
	('171', '190', '27', '5', '"A equipe foi comprometida na reforma do meu banheiro, mas seria vantajoso ter um acompanhamento pós-obra para garantir que todos os detalhes foram finalizados conforme acordado."'),
	('172', '164', '4', '2', '"Embora a comunicação tenha sido clara, seria útil oferecer um serviço de assistência técnica por um período após a conclusão da reforma, para resolver eventuais problemas que possam surgir."'),
	('173', '107', '11', '1', '"A qualidade do serviço foi boa, no entanto, seria valioso disponibilizar um catálogo mais amplo de fornecedores de materiais para dar mais opções aos clientes na escolha dos materiais."'),
	('174', '78', '6', '4', '"Apesar da eficiência na execução, seria interessante oferecer um serviço de gerenciamento de resíduos mais robusto, visando a sustentabilidade e o descarte responsável dos materiais utilizados."'),
	('175', '117', '3', '1', '"A equipe foi prestativa na reforma da minha cozinha, mas seria útil oferecer um programa de fidelidade ou indicação para clientes frequentes, incentivando sua fidelização."'),
	('176', '144', '6', '1', '"Embora tenham entregado dentro do prazo, seria vantajoso disponibilizar um serviço de prévia virtual do projeto, utilizando tecnologias de realidade aumentada para visualização mais precisa."'),
	('177', '2', '26', '3', '"A atenção aos detalhes foi boa, mas seria valioso oferecer um serviço de consultoria em decoração após a conclusão da reforma, para ajudar os clientes na ambientação do espaço."'),
	('178', '113', '8', '4', '"Apesar da organização, seria interessante oferecer um serviço de garantia estendida para os materiais utilizados, assegurando aos clientes uma maior tranquilidade após a conclusão da obra."'),
	('179', '101', '15', '2', '"A equipe foi comprometida na reforma do meu escritório, mas seria benéfico ter um sistema de gestão online, onde os clientes pudessem acompanhar o progresso e fazer comentários em tempo real."'),
	('180', '60', '4', '1', '"Apesar da limpeza final, seria útil oferecer um serviço de manutenção preventiva para as instalações, ajudando os clientes a prolongarem a vida útil dos novos elementos da reforma."'),
	('181', '99', '1', '4', '"A comunicação foi clara, mas seria valioso oferecer um serviço de atendimento pós-obra com um canal exclusivo para dúvidas ou emergências que possam surgir após a conclusão do projeto."'),
	('182', '80', '21', '1', 'Equipe altamente profissional! Cumpriram o prazo e o resultado da reforma da minha cozinha ficou incrível. Recomendo totalmente.'),
	('183', '111', '30', '4', 'Contratei-os para uma reforma de banheiro e fiquei muito satisfeito com o resultado final. Ótimo trabalho e atenção aos detalhes.'),
	('184', '114', '8', '3', '"Excelente serviço de construção! Desde o planejamento até a execução, tudo foi feito com cuidado e competência. Muito obrigado!"'),
	('185', '6', '29', '1', 'Profissionais pontuais e qualificados. Transformaram minha área externa de forma surpreendente. Recomendo!'),
	('186', '59', '29', '4', 'A reforma do meu escritório foi concluída no prazo e com excelente qualidade. Equipe comprometida e eficiente.'),
	('187', '134', '17', '3', 'Contratei-os para uma pequena reforma em casa e fiquei impressionado com o profissionalismo e a dedicação da equipe. Recomendo de olhos fechados!'),
	('188', '93', '24', '2', 'Serviço de construção excepcional! A equipe foi além das expectativas e entregou um trabalho de alta qualidade dentro do prazo estipulado.'),
	('189', '199', '22', '5', 'Estou muito contente com a reforma da minha sala. Profissionais atenciosos e habilidosos. Recomendo a todos!'),
	('190', '161', '15', '2', 'Equipe extremamente competente na execução da reforma da minha varanda. Preço justo e resultado final incrível!'),
	('191', '25', '3', '2', 'Serviço de construção impecável! Profissionais qualificados e comprometidos. Superaram minhas expectativas.'),
	('192', '118', '25', '1', 'Contratei-os para uma reforma em casa e o resultado foi além do esperado. Profissionais dedicados e serviço de alta qualidade.'),
	('193', '171', '2', '4', 'A empresa demonstrou grande expertise na reforma do meu apartamento. Pontualidade e comprometimento foram marcas do serviço prestado.'),
	('194', '54', '30', '1', 'Profissionais responsáveis e capacitados. A reforma do meu escritório foi realizada com eficiência e qualidade.'),
	('195', '104', '23', '4', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('196', '46', '14', '5', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('197', '90', '29', '3', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('198', '166', '2', '4', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('199', '39', '8', '1', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('200', '171', '8', '3', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('201', '91', '16', '2', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('202', '92', '12', '5', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('203', '177', '28', '1', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('204', '135', '7', '4', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('205', '135', '30', '4', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('206', '121', '27', '3', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('207', '114', '8', '4', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('208', '107', '12', '5', '"Apesar do bom serviço na reforma da área externa, a comunicação sobre mudanças no projeto foi pouco eficiente. Melhor articulação entre cliente e equipe seria vantajosa."'),
	('209', '141', '19', '2', '"A reforma da minha varanda teve um resultado satisfatório, mas a falta de comprometimento com prazos foi um problema. Maior responsabilidade na gestão do tempo é crucial."'),
	('210', '142', '28', '5', '"Houve um bom esforço na execução da construção, mas a falta de supervisão levou a alguns erros na fase inicial. Sugiro mais controle de qualidade desde o início do projeto."'),
	('211', '147', '16', '3', '"A equipe foi atenciosa na reforma do meu apartamento, no entanto, a falta de sugestões criativas para otimização do espaço foi notável. Mais proatividade seria interessante."'),
	('212', '40', '27', '5', '"Contratei-os para uma reforma em casa. Apesar da qualidade do serviço, houve falta de transparência em relação aos materiais utilizados. Maior clareza seria positiva."'),
	('213', '36', '10', '1', '"O serviço de construção atendeu às expectativas, mas a ausência de um plano de contingência para imprevistos prejudicou o andamento do projeto. Melhor preparação é necessária."'),
	('214', '26', '24', '3', '"A equipe foi competente na reforma do meu escritório, no entanto, houve dificuldades na comunicação sobre alterações no projeto. Melhorias na comunicação são essenciais."'),
	('215', '5', '17', '5', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('216', '114', '24', '1', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('217', '110', '11', '4', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('218', '77', '26', '5', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('219', '71', '9', '1', 'Equipe altamente profissional! Cumpriram o prazo e o resultado da reforma da minha cozinha ficou incrível. Recomendo totalmente.'),
	('220', '73', '28', '5', 'Contratei-os para uma reforma de banheiro e fiquei muito satisfeito com o resultado final. Ótimo trabalho e atenção aos detalhes.'),
	('221', '48', '8', '1', '"Excelente serviço de construção! Desde o planejamento até a execução, tudo foi feito com cuidado e competência. Muito obrigado!"'),
	('222', '184', '18', '5', 'Profissionais pontuais e qualificados. Transformaram minha área externa de forma surpreendente. Recomendo!'),
	('223', '110', '23', '1', 'A reforma do meu escritório foi concluída no prazo e com excelente qualidade. Equipe comprometida e eficiente.'),
	('224', '139', '18', '1', 'Contratei-os para uma pequena reforma em casa e fiquei impressionado com o profissionalismo e a dedicação da equipe. Recomendo de olhos fechados!'),
	('225', '172', '22', '5', 'Serviço de construção excepcional! A equipe foi além das expectativas e entregou um trabalho de alta qualidade dentro do prazo estipulado.'),
	('226', '95', '16', '4', 'Estou muito contente com a reforma da minha sala. Profissionais atenciosos e habilidosos. Recomendo a todos!'),
	('227', '104', '3', '5', 'Equipe extremamente competente na execução da reforma da minha varanda. Preço justo e resultado final incrível!'),
	('228', '115', '20', '5', 'Serviço de construção impecável! Profissionais qualificados e comprometidos. Superaram minhas expectativas.'),
	('229', '4', '21', '1', 'Contratei-os para uma reforma em casa e o resultado foi além do esperado. Profissionais dedicados e serviço de alta qualidade.'),
	('230', '177', '27', '4', 'A empresa demonstrou grande expertise na reforma do meu apartamento. Pontualidade e comprometimento foram marcas do serviço prestado.'),
	('231', '132', '28', '1', 'Profissionais responsáveis e capacitados. A reforma do meu escritório foi realizada com eficiência e qualidade.'),
	('232', '114', '6', '1', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('233', '172', '29', '2', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('234', '141', '10', '2', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('235', '183', '6', '3', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('236', '41', '27', '4', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('237', '118', '5', '3', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('238', '1', '11', '1', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('239', '65', '16', '4', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('240', '166', '2', '5', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('241', '96', '27', '1', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('242', '171', '23', '1', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('243', '67', '16', '4', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('244', '146', '15', '5', '"O serviço de construção foi satisfatório, porém, a falta de sugestões criativas para otimização do espaço foi notável. Mais proatividade seria interessante."'),
	('245', '132', '26', '2', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('246', '62', '15', '3', '"Apesar do bom serviço na reforma da área externa, a comunicação sobre mudanças no projeto foi pouco eficiente. Melhor articulação entre cliente e equipe seria vantajosa."'),
	('247', '200', '14', '5', '"A reforma da minha varanda teve um resultado satisfatório, mas a falta de comprometimento com prazos foi um problema. Maior responsabilidade na gestão do tempo é crucial."'),
	('248', '45', '28', '4', '"Houve um bom esforço na execução da construção, mas a falta de supervisão levou a alguns erros na fase inicial. Sugiro mais controle de qualidade desde o início do projeto."'),
	('249', '85', '18', '1', '"A equipe foi atenciosa na reforma do meu apartamento, no entanto, a falta de cuidado na proteção de áreas adjacentes durante a obra foi notável. Maior zelo é necessário."'),
	('250', '136', '13', '2', '"Contratei-os para uma reforma em casa. Apesar da qualidade do serviço, houve falta de transparência em relação aos materiais utilizados. Maior clareza seria positiva."'),
	('251', '67', '16', '2', '"O serviço de construção atendeu às expectativas, mas a ausência de um plano de contingência para imprevistos prejudicou o andamento do projeto. Melhor preparação é necessária."'),
	('252', '6', '10', '3', '"A equipe foi competente na reforma do meu escritório, no entanto, houve dificuldades na comunicação sobre alterações no projeto. Melhorias na comunicação são essenciais."'),
	('253', '104', '8', '2', '"A reforma do meu banheiro teve um bom resultado final, porém, a falta de acompanhamento regular do progresso gerou incertezas. Recomendo maior feedback ao cliente."'),
	('254', '61', '21', '2', '"Embora tenham entregado a construção no prazo, houve problemas com a qualidade de alguns materiais utilizados. Sugiro maior atenção à seleção de materiais de melhor qualidade."'),
	('255', '66', '23', '1', '"A equipe foi comprometida na reforma da minha cozinha, mas alguns detalhes de acabamento foram negligenciados. Melhor atenção aos detalhes é fundamental."'),
	('256', '138', '15', '1', '"O serviço de construção foi satisfatório, porém, houve falta de cuidado na proteção de áreas adjacentes durante a obra. Maior zelo com o ambiente é necessário."'),
	('257', '98', '28', '1', '"Apesar do resultado final da reforma ter sido positivo, a falta de flexibilidade para ajustes no projeto foi um obstáculo. Sugiro maior adaptabilidade"'),
	('258', '1', '4', '1', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('259', '63', '15', '1', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('260', '47', '22', '4', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('261', '46', '6', '2', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('262', '16', '30', '3', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('263', '146', '22', '5', '"O serviço de construção foi satisfatório, mas houve divergências no orçamento inicial e final. Recomendo mais clareza nos custos extras durante o projeto."'),
	('264', '35', '9', '3', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('265', '56', '24', '5', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('266', '185', '23', '3', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('267', '66', '14', '3', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('268', '188', '16', '1', '"A equipe foi pontual e comprometida na reforma do meu banheiro, porém, seria vantajoso oferecer opções mais sustentáveis de materiais para escolha dos clientes, alinhando-se às tendências ambientais."'),
	('269', '110', '29', '4', '"O serviço de construção foi bem executado, no entanto, seria benéfico ter mais disponibilidade para reuniões intermediárias durante o projeto, para alinhar expectativas e ajustar detalhes conforme necessário."'),
	('270', '166', '5', '4', '"A reforma da minha cozinha teve um ótimo resultado, mas seria interessante oferecer um portfólio mais diversificado de designs e estilos para inspirar os clientes na concepção do projeto."'),
	('271', '144', '2', '2', '"Embora a equipe tenha sido atenciosa durante a construção, seria útil ter um sistema de comunicação mais eficiente para que o cliente possa acompanhar o progresso em tempo real, garantindo maior transparência."'),
	('272', '65', '14', '3', '"O serviço prestado na reforma do meu escritório foi de qualidade, porém, seria valioso oferecer pacotes ou descontos para projetos maiores, incentivando os clientes a realizarem mais melhorias de uma vez."'),
	('273', '181', '12', '2', '"Houve dedicação na construção, mas seria útil oferecer um serviço pós-obra, como um manual de manutenção ou garantia estendida, para garantir a durabilidade do trabalho realizado."'),
	('274', '57', '5', '1', '"A equipe foi diligente na reforma da minha casa, no entanto, seria interessante oferecer opções de financiamento ou parcelamento, tornando o serviço mais acessível a diferentes perfis de clientes."'),
	('275', '157', '15', '2', '"Apesar da qualidade do serviço, seria valioso disponibilizar um canal de feedback estruturado para os clientes expressarem suas necessidades e sugestões durante o processo de reforma."'),
	('276', '105', '5', '1', '"O resultado da construção foi satisfatório, porém, seria benéfico oferecer um serviço de consultoria adicional para otimização de espaços, agregando ainda mais valor ao projeto."'),
	('277', '171', '21', '3', '"A equipe foi comprometida na reforma do meu banheiro, mas seria vantajoso ter um acompanhamento pós-obra para garantir que todos os detalhes foram finalizados conforme acordado."'),
	('278', '52', '27', '4', '"Apesar da qualidade do serviço, seria valioso disponibilizar um canal de feedback estruturado para os clientes expressarem suas necessidades e sugestões durante o processo de reforma."'),
	('279', '78', '10', '1', '"O resultado da construção foi satisfatório, porém, seria benéfico oferecer um serviço de consultoria adicional para otimização de espaços, agregando ainda mais valor ao projeto."'),
	('280', '74', '12', '3', '"A equipe foi comprometida na reforma do meu banheiro, mas seria vantajoso ter um acompanhamento pós-obra para garantir que todos os detalhes foram finalizados conforme acordado."'),
	('281', '33', '6', '5', '"Embora a comunicação tenha sido clara, seria útil oferecer um serviço de assistência técnica por um período após a conclusão da reforma, para resolver eventuais problemas que possam surgir."'),
	('282', '36', '15', '1', '"A qualidade do serviço foi boa, no entanto, seria valioso disponibilizar um catálogo mais amplo de fornecedores de materiais para dar mais opções aos clientes na escolha dos materiais."'),
	('283', '196', '20', '3', '"Apesar da eficiência na execução, seria interessante oferecer um serviço de gerenciamento de resíduos mais robusto, visando a sustentabilidade e o descarte responsável dos materiais utilizados."'),
	('284', '63', '13', '3', '"A equipe foi prestativa na reforma da minha cozinha, mas seria útil oferecer um programa de fidelidade ou indicação para clientes frequentes, incentivando sua fidelização."'),
	('285', '8', '7', '3', '"Embora tenham entregado dentro do prazo, seria vantajoso disponibilizar um serviço de prévia virtual do projeto, utilizando tecnologias de realidade aumentada para visualização mais precisa."'),
	('286', '184', '24', '4', '"A atenção aos detalhes foi boa, mas seria valioso oferecer um serviço de consultoria em decoração após a conclusão da reforma, para ajudar os clientes na ambientação do espaço."'),
	('287', '92', '18', '3', '"Apesar da organização, seria interessante oferecer um serviço de garantia estendida para os materiais utilizados, assegurando aos clientes uma maior tranquilidade após a conclusão da obra."'),
	('288', '86', '19', '5', '"A equipe foi comprometida na reforma do meu escritório, mas seria benéfico ter um sistema de gestão online, onde os clientes pudessem acompanhar o progresso e fazer comentários em tempo real."'),
	('289', '78', '9', '3', '"Apesar da limpeza final, seria útil oferecer um serviço de manutenção preventiva para as instalações, ajudando os clientes a prolongarem a vida útil dos novos elementos da reforma."'),
	('290', '66', '30', '1', '"A comunicação foi clara, mas seria valioso oferecer um serviço de atendimento pós-obra com um canal exclusivo para dúvidas ou emergências que possam surgir após a conclusão do projeto."'),
	('291', '37', '1', '1', 'Equipe altamente profissional! Cumpriram o prazo e o resultado da reforma da minha cozinha ficou incrível. Recomendo totalmente.'),
	('292', '106', '26', '1', 'Contratei-os para uma reforma de banheiro e fiquei muito satisfeito com o resultado final. Ótimo trabalho e atenção aos detalhes.'),
	('293', '59', '18', '4', '"Excelente serviço de construção! Desde o planejamento até a execução, tudo foi feito com cuidado e competência. Muito obrigado!"'),
	('294', '20', '24', '4', 'Profissionais pontuais e qualificados. Transformaram minha área externa de forma surpreendente. Recomendo!'),
	('295', '105', '28', '1', 'A reforma do meu escritório foi concluída no prazo e com excelente qualidade. Equipe comprometida e eficiente.'),
	('296', '51', '12', '1', 'Contratei-os para uma pequena reforma em casa e fiquei impressionado com o profissionalismo e a dedicação da equipe. Recomendo de olhos fechados!'),
	('297', '74', '30', '3', 'Serviço de construção excepcional! A equipe foi além das expectativas e entregou um trabalho de alta qualidade dentro do prazo estipulado.'),
	('298', '184', '15', '5', 'Estou muito contente com a reforma da minha sala. Profissionais atenciosos e habilidosos. Recomendo a todos!'),
	('299', '118', '27', '4', 'Equipe extremamente competente na execução da reforma da minha varanda. Preço justo e resultado final incrível!'),
	('300', '129', '1', '4', 'Serviço de construção impecável! Profissionais qualificados e comprometidos. Superaram minhas expectativas.'),
	('301', '186', '26', '2', 'Contratei-os para uma reforma em casa e o resultado foi além do esperado. Profissionais dedicados e serviço de alta qualidade.'),
	('302', '86', '14', '4', 'A empresa demonstrou grande expertise na reforma do meu apartamento. Pontualidade e comprometimento foram marcas do serviço prestado.'),
	('303', '37', '8', '4', 'Profissionais responsáveis e capacitados. A reforma do meu escritório foi realizada com eficiência e qualidade.'),
	('304', '142', '18', '1', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('305', '101', '21', '3', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('306', '8', '4', '5', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('307', '124', '21', '3', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('308', '72', '14', '4', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('309', '157', '19', '5', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('310', '3', '5', '4', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('311', '171', '21', '1', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('312', '179', '11', '2', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('313', '177', '18', '3', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('314', '26', '19', '3', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('315', '126', '20', '1', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('316', '71', '3', '4', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('317', '116', '28', '1', '"Apesar do bom serviço na reforma da área externa, a comunicação sobre mudanças no projeto foi pouco eficiente. Melhor articulação entre cliente e equipe seria vantajosa."'),
	('318', '138', '3', '1', '"A reforma da minha varanda teve um resultado satisfatório, mas a falta de comprometimento com prazos foi um problema. Maior responsabilidade na gestão do tempo é crucial."'),
	('319', '14', '30', '1', '"Houve um bom esforço na execução da construção, mas a falta de supervisão levou a alguns erros na fase inicial. Sugiro mais controle de qualidade desde o início do projeto."'),
	('320', '19', '7', '2', '"A equipe foi atenciosa na reforma do meu apartamento, no entanto, a falta de sugestões criativas para otimização do espaço foi notável. Mais proatividade seria interessante."'),
	('321', '27', '9', '2', '"Contratei-os para uma reforma em casa. Apesar da qualidade do serviço, houve falta de transparência em relação aos materiais utilizados. Maior clareza seria positiva."'),
	('322', '158', '6', '4', '"O serviço de construção atendeu às expectativas, mas a ausência de um plano de contingência para imprevistos prejudicou o andamento do projeto. Melhor preparação é necessária."'),
	('323', '110', '8', '4', '"A equipe foi competente na reforma do meu escritório, no entanto, houve dificuldades na comunicação sobre alterações no projeto. Melhorias na comunicação são essenciais."'),
	('324', '2', '19', '1', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('325', '177', '11', '2', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('326', '62', '22', '4', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('327', '185', '21', '2', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('328', '101', '12', '1', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('329', '83', '14', '3', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('330', '150', '23', '2', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('331', '160', '14', '4', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('332', '35', '16', '2', '"A equipe foi pontual e comprometida na reforma do meu banheiro, porém, seria vantajoso oferecer opções mais sustentáveis de materiais para escolha dos clientes, alinhando-se às tendências ambientais."'),
	('333', '101', '23', '5', '"O serviço de construção foi bem executado, no entanto, seria benéfico ter mais disponibilidade para reuniões intermediárias durante o projeto, para alinhar expectativas e ajustar detalhes conforme necessário."'),
	('334', '67', '19', '4', '"A reforma da minha cozinha teve um ótimo resultado, mas seria interessante oferecer um portfólio mais diversificado de designs e estilos para inspirar os clientes na concepção do projeto."'),
	('335', '88', '1', '4', '"Embora a equipe tenha sido atenciosa durante a construção, seria útil ter um sistema de comunicação mais eficiente para que o cliente possa acompanhar o progresso em tempo real, garantindo maior transparência."'),
	('336', '55', '6', '4', '"O serviço prestado na reforma do meu escritório foi de qualidade, porém, seria valioso oferecer pacotes ou descontos para projetos maiores, incentivando os clientes a realizarem mais melhorias de uma vez."'),
	('337', '30', '15', '3', '"Houve dedicação na construção, mas seria útil oferecer um serviço pós-obra, como um manual de manutenção ou garantia estendida, para garantir a durabilidade do trabalho realizado."'),
	('338', '118', '28', '1', '"A equipe foi diligente na reforma da minha casa, no entanto, seria interessante oferecer opções de financiamento ou parcelamento, tornando o serviço mais acessível a diferentes perfis de clientes."'),
	('339', '27', '17', '2', '"Apesar da qualidade do serviço, seria valioso disponibilizar um canal de feedback estruturado para os clientes expressarem suas necessidades e sugestões durante o processo de reforma."'),
	('340', '121', '19', '4', '"O resultado da construção foi satisfatório, porém, seria benéfico oferecer um serviço de consultoria adicional para otimização de espaços, agregando ainda mais valor ao projeto."'),
	('341', '156', '5', '4', '"A equipe foi comprometida na reforma do meu banheiro, mas seria vantajoso ter um acompanhamento pós-obra para garantir que todos os detalhes foram finalizados conforme acordado."'),
	('342', '173', '9', '1', '"Apesar da qualidade do serviço, seria valioso disponibilizar um canal de feedback estruturado para os clientes expressarem suas necessidades e sugestões durante o processo de reforma."'),
	('343', '75', '4', '1', '"O resultado da construção foi satisfatório, porém, seria benéfico oferecer um serviço de consultoria adicional para otimização de espaços, agregando ainda mais valor ao projeto."'),
	('344', '157', '1', '1', '"A equipe foi comprometida na reforma do meu banheiro, mas seria vantajoso ter um acompanhamento pós-obra para garantir que todos os detalhes foram finalizados conforme acordado."'),
	('345', '113', '14', '2', '"Embora a comunicação tenha sido clara, seria útil oferecer um serviço de assistência técnica por um período após a conclusão da reforma, para resolver eventuais problemas que possam surgir."'),
	('346', '78', '30', '2', '"A qualidade do serviço foi boa, no entanto, seria valioso disponibilizar um catálogo mais amplo de fornecedores de materiais para dar mais opções aos clientes na escolha dos materiais."'),
	('347', '173', '22', '4', '"Apesar da eficiência na execução, seria interessante oferecer um serviço de gerenciamento de resíduos mais robusto, visando a sustentabilidade e o descarte responsável dos materiais utilizados."'),
	('348', '191', '3', '2', '"A equipe foi prestativa na reforma da minha cozinha, mas seria útil oferecer um programa de fidelidade ou indicação para clientes frequentes, incentivando sua fidelização."'),
	('349', '87', '6', '4', '"Embora tenham entregado dentro do prazo, seria vantajoso disponibilizar um serviço de prévia virtual do projeto, utilizando tecnologias de realidade aumentada para visualização mais precisa."'),
	('350', '131', '11', '1', '"A atenção aos detalhes foi boa, mas seria valioso oferecer um serviço de consultoria em decoração após a conclusão da reforma, para ajudar os clientes na ambientação do espaço."'),
	('351', '24', '11', '4', '"Apesar da organização, seria interessante oferecer um serviço de garantia estendida para os materiais utilizados, assegurando aos clientes uma maior tranquilidade após a conclusão da obra."'),
	('352', '57', '17', '2', '"A equipe foi comprometida na reforma do meu escritório, mas seria benéfico ter um sistema de gestão online, onde os clientes pudessem acompanhar o progresso e fazer comentários em tempo real."'),
	('353', '128', '7', '5', '"Apesar da limpeza final, seria útil oferecer um serviço de manutenção preventiva para as instalações, ajudando os clientes a prolongarem a vida útil dos novos elementos da reforma."'),
	('354', '167', '3', '4', '"A comunicação foi clara, mas seria valioso oferecer um serviço de atendimento pós-obra com um canal exclusivo para dúvidas ou emergências que possam surgir após a conclusão do projeto."'),
	('355', '119', '11', '3', 'Equipe altamente profissional! Cumpriram o prazo e o resultado da reforma da minha cozinha ficou incrível. Recomendo totalmente.'),
	('356', '139', '26', '5', 'Contratei-os para uma reforma de banheiro e fiquei muito satisfeito com o resultado final. Ótimo trabalho e atenção aos detalhes.'),
	('357', '132', '6', '2', '"Excelente serviço de construção! Desde o planejamento até a execução, tudo foi feito com cuidado e competência. Muito obrigado!"'),
	('358', '53', '19', '4', 'Profissionais pontuais e qualificados. Transformaram minha área externa de forma surpreendente. Recomendo!'),
	('359', '157', '18', '2', 'A reforma do meu escritório foi concluída no prazo e com excelente qualidade. Equipe comprometida e eficiente.'),
	('360', '97', '8', '2', 'Contratei-os para uma pequena reforma em casa e fiquei impressionado com o profissionalismo e a dedicação da equipe. Recomendo de olhos fechados!'),
	('361', '146', '10', '1', 'Serviço de construção excepcional! A equipe foi além das expectativas e entregou um trabalho de alta qualidade dentro do prazo estipulado.'),
	('362', '130', '27', '5', 'Estou muito contente com a reforma da minha sala. Profissionais atenciosos e habilidosos. Recomendo a todos!'),
	('363', '109', '24', '1', 'Equipe extremamente competente na execução da reforma da minha varanda. Preço justo e resultado final incrível!'),
	('364', '158', '18', '4', 'Serviço de construção impecável! Profissionais qualificados e comprometidos. Superaram minhas expectativas.'),
	('365', '145', '5', '5', 'Contratei-os para uma reforma em casa e o resultado foi além do esperado. Profissionais dedicados e serviço de alta qualidade.'),
	('366', '10', '6', '2', 'A empresa demonstrou grande expertise na reforma do meu apartamento. Pontualidade e comprometimento foram marcas do serviço prestado.'),
	('367', '153', '16', '3', 'Profissionais responsáveis e capacitados. A reforma do meu escritório foi realizada com eficiência e qualidade.'),
	('368', '145', '2', '4', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('369', '132', '10', '3', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('370', '180', '21', '4', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('371', '64', '24', '1', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('372', '94', '13', '1', 'Equipe de construção altamente profissional. A reforma da minha casa foi concluída com perfeição.'),
	('373', '86', '22', '4', 'Serviço de reforma de extrema qualidade! Profissionais comprometidos e atenciosos com os detalhes.'),
	('374', '132', '3', '3', '"Excelente serviço de construção! Pontuais, competentes e entregaram o projeto conforme acordado. Recomendo sem dúvidas!"'),
	('375', '199', '13', '1', '"Embora tenham concluído a reforma da minha cozinha dentro do prazo, alguns detalhes ficaram negligenciados. Precisam melhorar a atenção aos acabamentos."'),
	('376', '21', '16', '3', '"O serviço de construção foi satisfatório, mas a comunicação durante o processo poderia ter sido mais clara. Sugiro mais transparência nas etapas do projeto."'),
	('377', '64', '17', '2', '"A equipe foi pontual na reforma do meu banheiro, porém houve dificuldades na resolução de problemas imprevistos. Maior agilidade nas soluções seria benéfica."'),
	('378', '20', '29', '5', '"Contratei-os para um projeto de construção. Embora o resultado final tenha sido bom, houve atrasos na entrega. Melhorias no cumprimento dos prazos são necessárias."'),
	('379', '186', '17', '3', '"A reforma do meu escritório teve um bom acabamento, mas houve desafios na coordenação entre os profissionais envolvidos. Sugiro melhor organização entre as equipes."'),
	('380', '94', '20', '2', '"Pontualidade foi um ponto forte na reforma da minha casa, porém, a limpeza pós-obra deixou a desejar. Sugiro mais atenção nesse aspecto para uma melhor experiência."'),
	('381', '119', '27', '1', '"Apesar do bom serviço na reforma da área externa, a comunicação sobre mudanças no projeto foi pouco eficiente. Melhor articulação entre cliente e equipe seria vantajosa."'),
	('382', '91', '18', '3', '"A reforma da minha varanda teve um resultado satisfatório, mas a falta de comprometimento com prazos foi um problema. Maior responsabilidade na gestão do tempo é crucial."'),
	('383', '41', '20', '1', '"Houve um bom esforço na execução da construção, mas a falta de supervisão levou a alguns erros na fase inicial. Sugiro mais controle de qualidade desde o início do projeto."'),
	('384', '117', '27', '3', '"A equipe foi atenciosa na reforma do meu apartamento, no entanto, a falta de sugestões criativas para otimização do espaço foi notável. Mais proatividade seria interessante."'),
	('385', '157', '7', '4', '"Contratei-os para uma reforma em casa. Apesar da qualidade do serviço, houve falta de transparência em relação aos materiais utilizados. Maior clareza seria positiva."'),
	('386', '85', '14', '3', '"O serviço de construção atendeu às expectativas, mas a ausência de um plano de contingência para imprevistos prejudicou o andamento do projeto. Melhor preparação é necessária."'),
	('387', '3', '13', '2', '"A equipe foi competente na reforma do meu escritório, no entanto, houve dificuldades na comunicação sobre alterações no projeto. Melhorias na comunicação são essenciais."'),
	('388', '147', '26', '4', '"Recomendo fortemente! Equipe de construção comprometida e competente, entregaram o projeto de acordo com o planejado."'),
	('389', '66', '25', '5', 'Estou muito satisfeito com a reforma do meu banheiro. Profissionais ágeis e cuidadosos. Ótimo trabalho!'),
	('390', '172', '11', '5', 'Serviço de construção excepcional! Profissionais dedicados que entregaram um projeto além das expectativas.'),
	('391', '62', '27', '4', 'A reforma da minha cozinha foi feita com rapidez e qualidade. Profissionais competentes e comprometidos com o resultado.'),
	('392', '5', '21', '5', '"Apesar da organização, seria interessante oferecer um serviço de garantia estendida para os materiais utilizados, assegurando aos clientes uma maior tranquilidade após a conclusão da obra."'),
	('393', '172', '6', '5', '"A equipe foi comprometida na reforma do meu escritório, mas seria benéfico ter um sistema de gestão online, onde os clientes pudessem acompanhar o progresso e fazer comentários em tempo real."'),
	('394', '80', '13', '5', '"Apesar da limpeza final, seria útil oferecer um serviço de manutenção preventiva para as instalações, ajudando os clientes a prolongarem a vida útil dos novos elementos da reforma."'),
	('395', '12', '20', '1', '"A comunicação foi clara, mas seria valioso oferecer um serviço de atendimento pós-obra com um canal exclusivo para dúvidas ou emergências que possam surgir após a conclusão do projeto."'),
	('396', '70', '24', '3', 'Equipe altamente profissional! Cumpriram o prazo e o resultado da reforma da minha cozinha ficou incrível. Recomendo totalmente.'),
	('397', '72', '18', '4', 'Contratei-os para uma reforma de banheiro e fiquei muito satisfeito com o resultado final. Ótimo trabalho e atenção aos detalhes.'),
	('398', '117', '20', '3', '"Excelente serviço de construção! Desde o planejamento até a execução, tudo foi feito com cuidado e competência. Muito obrigado!"'),
	('399', '159', '17', '2', 'Profissionais pontuais e qualificados. Transformaram minha área externa de forma surpreendente. Recomendo!'),
	('400', '94', '11', '4', 'A reforma do meu escritório foi concluída no prazo e com excelente qualidade. Equipe comprometida e eficiente.');

UPDATE prestador
SET nota_media = (
 SELECT AVG(nota_avaliacao)
 FROM avaliacao
 WHERE avaliado_id = prestador.prestador_id
);
